name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: npm install

      - name: Run tests and  save output
        run: |
          npm run check &> test_report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: test_report.txt

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Create deployment directory
        run: mkdir -p ~/ostad

      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: test-report
          path: ~/ostad

      - name: Display artifact
        run: |
          echo "Files in ~/ostad:"
          ls -l ~/ostad
          echo ""
          echo "===== test-report====="
          cat ~/ostad/test_report.txt

      - name: Deploy latest code
        run: |
          cd /home/ubuntu/rony_cicd_assignment

          git pull origin main

          npm install

          pm2 restart node-app:3000

          pm2 save

          pm2 status
